### ISSUE TITLE
Fix Outline Formatting

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-datascience.myst#10]
Right now, it's some weird standalone highlighted block. 

It should look like a normal section, analogous to the current live lectures. 

edit: cut section as outline on side

**Comment by arnavs** [comment]
See: 

Weird: https://quantecon.github.io/lecture-datascience.myst/introduction/getting_started.html vs. 
Good: https://datascience.quantecon.org/introduction/getting_started.html

**Comment by arnavs** [comment]
They spent some time on this, not easy to do. Might just cut the section now that outline is on the side.

**Comment by aadsouza** [comment]
see #25 #26 #27 #28
