### ISSUE TITLE
Doublecheck that there are no relative paths in notebooks

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-datascience.myst#109]
Ideally all static assets are just links to the HTML deployment - which I would hope is relaitively easy?  If not then full urls to the github notebooks is ffine.

**Comment by aadsouza** [comment]
i think there's only one instance where we had a messy fix to a solution that is given out in the reshape lecture. chose to put it in `_static` instead of `pd` so users don't "accidentally" open it up prior to reading the question. nevertheless it's a full url.
```Don't spend too much time on this... if you get stuck, you will find our answer [here](https://github.com/QuantEcon/lecture-datascience.myst/raw/main/src/_static/reshape-ex1-ans.txt).```

**Comment by aadsouza** [comment]
just went through the nbs for the lectures + pses, they all seem to be full urls as `ds.qe.org/PATH` except for the upstreamed issue https://github.com/QuantEcon/lecture-datascience.myst/issues/88#issuecomment-836084641.

**Comment by WenxinM** [comment]
Double-checked. All look good except for the issue @aadsouza brought up.
