### ISSUE TITLE
Exercise ````

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-datascience.myst#11]
Many of the exercise directives are preceded by four tick marks (see below). 

```
````{exercise}
```

But they aren't closed with four tick marks, which leads to formatting errors.

**Comment by aadsouza** [comment]
@WenxinM and I have pushed updates. There was a slight hiccup where I accidentally mixed in the application stuff into the pandas repo but it has been fixed. Noticed that `code-block` renders in `exercise` directives whereas `code-cell` does not and hence changes made.
