### ISSUE TITLE
Ensure that things don't deploy if there is a failure (unit test or otherwise)

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-datascience.myst#110]
That is, it looks to me like the https://github.com/QuantEcon/lecture-datascience.myst/pull/106  PR looks good, deplyed on netflify, etc.
We would want some way to know that things went wrong, or the unit test isn't useful.

**Comment by jlperla** [comment]
It seems like maybe right at after https://github.com/QuantEcon/lecture-datascience.myst/blob/main/.github/workflows/netlify.yml#L27 you want to scan to look for any errors in the build output with a simple shell script/grid/etc., right? And then fail the process prior to the deployment to netflify?

We would want it to fail and not deploy for all cases, not just ones flagged like a "unit test".

**Comment by AakashGfude** [comment]
@jlperla we can force things to break if something goes wrong, by using the `-W` flag in `jb build` .The flag means `warning treated as error`. Using this the build will fail if there is any warning. Since the execution failure of a document is also shown as a warning, it needs a `-W` flag to treat it as an error.

**Comment by jlperla** [comment]
Ok, but aren't there going to be all sorts of more minor warnings that are fine to ignore, or is it completely clean?

I just remember all sorts of relatively innocuous warnings with the sphinx rst stuff

**Comment by AakashGfude** [comment]
@jlperla I fear all warnings, no matter how small, will be treated as errors. For a build to work then, we will need to have a clean slate. The most commonplace for `-W` to be used is in the test suite.

**Comment by jlperla** [comment]
Sure, but if you need to have zero warnijgs In the PR you use for the test, then you need to have zero warnings everywhere because you edit in PRs

Is there a way to make code errors an actual a error? If those aren't an error, I don't what would be.

I guess it all depends on how easy it is to be warning free. But I just remember it being very difficult in the old incarnation. Are we warning free right now, for example?

**Comment by mmcky** [comment]
> Is there a way to make code errors an actual a error?

Not yet but it is a feature request and will be added at some point (but is currently a `medium` term priority) given the current approach is to ensure warning free builds (generally) and catching them using `-W`. The warnings become really useful once there aren't any :-)

**Comment by aadsouza** [comment]
> I guess it all depends on how easy it is to be warning free. But I just remember it being very difficult in the old incarnation. Are we warning free right now, for example?

We're not warning free right now. There's still some minor stuff that we pushed for `later`. For example, we need to add some sort of `orphan` tag on the PSes to allow them to be out of the `toc` without triggering a warning.

**Comment by jlperla** [comment]
Ok, then let me ask: is it even possible to be warning free right now? Or are there a bunch of bugs/features/etc that need to be implemented in jupyterbook?

**Comment by aadsouza** [comment]
should be warning free once #131 and #132 are merged in. thanks @mmcky :grin:
