### ISSUE TITLE
Document or verify that a local build of the jupyterbook sees unit test and other failures

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-datascience.myst#112]
This is really spun out of #84 and maybe it is complete.

But basically, given that the error message is found in the build cache, it is important that we can see this clearly when running a local build and know things are wrong (i.e. we don't need to wait until #110  is done)  and don't have to manually parse a file

So maybe this is just a quetsion of documenting or pointing out where the errors would be seen - and this might already be done.

**Comment by aadsouza** [comment]
build on main branch -> [actions](https://github.com/QuantEcon/lecture-datascience.myst/actions) -> under the workflow that `Build[s] & Publish[es] to GH Pages`, download `build-cache` -> html -> reports -> $\exists$ `log` file[s] with errors.

**Comment by aadsouza** [comment]
Terminal indeed shows that something went wrong during local build and directs user to log file.
```
WARNING: Execution Failed with traceback saved in /Users/USERNAME/lecture-datascience.myst/src/_build/html/reports/visualization_rules.log
```
