### ISSUE TITLE
add background to png to support dark mode

### ISSUE THREAD

**Issue by aadsouza** [QuantEcon/lecture-datascience.myst#116]
add a background to these images or change them to a grey font. found here https://datascience.quantecon.org/assets/_static/intro_files/PandasSeries.png and https://datascience.quantecon.org/assets/_static/intro_files/PandasDataFrame.png

**Comment by WenxinM** [comment]
The white background has been added (see PR) but the references in the md files have not been changed

**Comment by aadsouza** [comment]
@arnavs we probably need to add these to the assets collection at ds.qe.org (along with the reshape answer thing) in order to minimize stuff in `_static`
