### ISSUE TITLE
Cleanup Issues General 

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-datascience.myst#12]
- moving files 

```
WARNING: logo file '_static/qe-logo.png' does not exist
WARNING: favicon file '_static/lectures-favicon.ico' does not exist
```

- toctree documentation thnig

**Comment by aadsouza** [comment]
Also
```
.../lecture-datascience.myst/src/introduction/overview.md:40: WARNING: 'myst' reference target not found: /projects.html
```
Page showing projects by past students needs to be moved.

**Comment by aadsouza** [comment]
and more stuff to transfer:
```
WARNING: unsupported theme option 'header_organisation_url' given
WARNING: unsupported theme option 'header_organisation' given
WARNING: unsupported theme option 'nb_repository_url' given
WARNING: unsupported theme option 'twitter' given
WARNING: unsupported theme option 'twitter_logo_url' given
WARNING: unsupported theme option 'og_logo_url' given
WARNING: unsupported theme option 'description' given
WARNING: unsupported theme option 'keywords' given
```

**Comment by aadsouza** [comment]
https://quantecon.github.io/lecture-datascience.myst/applications/working_with_text.html going to add this here. Probably need to bring in the avalanche incidents `.csv`.

**Comment by arnavs** [comment]
I think that CSV is generated by the lecture. We shouldn’t need to have it saved. I will investigate; could be that’s not happening on GH actions

**Comment by aadsouza** [comment]
> Also
> 
> ```
> .../lecture-datascience.myst/src/introduction/overview.md:40: WARNING: 'myst' reference target not found: /projects.html
> ```
> 
> Page showing projects by past students needs to be moved.

resolved

**Comment by WenxinM** [comment]
We still have the warnings on the unsupported theme options, which might be fixed after merging the PR by Aakash

**Comment by arnavs** [comment]
Reorganizing issues a bit
