### ISSUE TITLE
Change `src` to `lectures` 

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-datascience.myst#120]
We have adopted a standard name of `lectures` 

https://github.com/quantEcon/lecture-python.myst

for the `src` directly. It makes `actions` more universal if we can adopt that name

**Comment by aadsouza** [comment]
need to make sure that nothing in the `md` files that relies on `src` breaks

**Comment by aadsouza** [comment]
closing this - everything seems to be stable thus far
