### ISSUE TITLE
test using syzygy

### ISSUE THREAD

**Issue by aadsouza** [QuantEcon/lecture-datascience.myst#128]

**Comment by wupeifan** [comment]
In particular the `ubc.syzygy.ca` one. I got the following error message, and nothing was pulled after.

![Capture](https://user-images.githubusercontent.com/6218238/120399325-a0c2e980-c2f0-11eb-9204-36b5aa41ab61.PNG)

**Comment by wupeifan** [comment]
If, instead of typing `https://ubc.syzygy.ca/jupyter/user/wupeifan/` I do `https://ubc.syzygy.ca/` instead, then it echos with the "no master branch" issue that Arnav mentioned.

![Capture](https://user-images.githubusercontent.com/6218238/120399476-f4cdce00-c2f0-11eb-8d80-440557f8be52.PNG)

**Comment by aadsouza** [comment]
@mmcky would this be fixed [here](https://github.com/QuantEcon/quantecon-book-theme/blob/9f85431237fbc2600222749dfcdc1115ea531a22/quantecon_book_theme/layout.html)?

**Comment by mmcky** [comment]
@aadsouza double check on the latest build but I think this is not fixed. You can specify `main` and `master` via `_config.yml` file now if needed.

**Comment by mmcky** [comment]
There are some additional updates in `quantecon-book-theme` that will make it more robust where `https` is optional as well.

**Comment by aadsouza** [comment]
like so https://github.com/QuantEcon/lecture-datascience.myst/pull/130 ? @mmcky

**Comment by mmcky** [comment]
cc: @AakashGfude

**Comment by AakashGfude** [comment]
@aadsouza sorry for getting back to you so late. the `config` variable is `repository_branch` like so:
```
sphinx:
  config:
    html_theme_options:
      repository_branch: main
```

**Comment by aadsouza** [comment]
tested with `https://ubc.syzygy.ca` and `https://pims.syzygy.ca`. seems to work now, possibly after update to `env.yml` 
```
-  - git+https://github.com/QuantEcon/quantecon-book-theme@jupyterlab
+  - quantecon-book-theme>=0.2.2,<0.3.0
```
