### ISSUE TITLE
Adjust size of logo in right page TOC 

### ISSUE THREAD

**Issue by DrDrij** [QuantEcon/lecture-datascience.myst#138]
The right column could use a little tidy after migration into `quantecon-book-theme`.

![image](https://user-images.githubusercontent.com/5886045/120571190-f1efec00-c45c-11eb-8bfe-2c90efe61122.png)

**Comment by aadsouza** [comment]
that the left edge of the `favicon` aligns with the grey bar above is consistent with `lecture-py`, but I agree that the size of the slot is not conducive to the `ds` `favicon`.

**Comment by aadsouza** [comment]
@mmcky would this be a fix for `qe-book-theme`?

**Comment by aadsouza** [comment]
@mmcky a sloppy fix from our end could be to add an invisible frame to the `favicon` png itself
