### ISSUE TITLE
missing latex formatting in `working_with_text`

### ISSUE THREAD

**Issue by aadsouza** [QuantEcon/lecture-datascience.myst#157]
might be related to https://github.com/QuantEcon/lecture-datascience.myst/issues/68
<img width="865" alt="Screen Shot 2021-06-16 at 12 10 16 AM" src="https://user-images.githubusercontent.com/59585791/122174041-3d2fd480-ce37-11eb-982c-41f93f11e917.png">

issue persists under both mathjax v2 and v3

**Comment by AakashGfude** [comment]
Interestng. This seems to work with CHTML but not SVG. cc: @mmcky

**Comment by AakashGfude** [comment]
Icons only in the particular page are messed up somehow

<img width="1789" alt="Screen Shot 2021-06-16 at 5 35 03 pm" src="https://user-images.githubusercontent.com/6542997/122177722-3a7dbf80-cec9-11eb-85f4-9cece56b99c5.png">

**Comment by aadsouza** [comment]
> Icons only in the particular page are messed up somehow
> 
> 
> 
> <img width="1789" alt="Screen Shot 2021-06-16 at 5 35 03 pm" src="https://user-images.githubusercontent.com/6542997/122177722-3a7dbf80-cec9-11eb-85f4-9cece56b99c5.png">
> 
> 

@AakashGfude yeah this was a part of #68

**Comment by AakashGfude** [comment]
fixed in https://github.com/QuantEcon/lecture-datascience.myst/pull/156
