### ISSUE TITLE
Remove extra folders from push to the notebooks repo

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-datascience.myst#158]
https://github.com/QuantEcon/lecture-datascience.notebooks/tree/main/_static  folder and https://github.com/QuantEcon/lecture-datascience.notebooks/tree/main/_panels_static 

Shouldn't be there.  Right @mmcky

**Comment by aadsouza** [comment]
@mmcky where do you want images now?
we didn't want to populate each of the directories with them.

**Comment by aadsouza** [comment]
@mmcky sounds good.

**Comment by jlperla** [comment]
@mmcky Is this how you are doing it for the python notebook repositories as well?  Using a copy of them in github rather than having them go off of the CDN one pushed out from the web?  Because if this is how you want to design things, we should close this issue.

But I would reconsider the architecture for serving static images on a CDN after jupyterbook gets first-class jupyter notebook support.  It seems like static assets should be shared between all output types of the book rather than replicated.

Besides the replication of the assets in two places which might be easy to get out of sync, my main concern is that git just isn't meant to hold binaries. because it balloons the size of the repo.  But if these things only add in a new commit rather than on every push to the repo, maybe it isn't so bad?

**Comment by mmcky** [comment]
This has been fixed in `.github/workflows/publish.yml`
