### ISSUE TITLE
Update the baseurl in config.yml before going live

### ISSUE THREAD

**Issue by Alim-faraji** [QuantEcon/lecture-datascience.myst#169]
Right now, the baseurl points to the `_notebooks` in gh-pages. However, because it is a nested link, there seems to be some confusion on parsing that address, and as a result the download notebook button on the toolbar misses a part of the link. This would not be an issue once we go live. Just remember to check that download notebook button again, once we go live.

**Comment by mmcky** [comment]
fixed by #170
