### ISSUE TITLE
[environment] Missing Data Files causing Execution Issues

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-datascience.myst#173]
The way the `environment.yml` has been setup seems fragile without many version pinnings. 

I also find it hard to replicate `locally` (i.e. something in this `environment.yml` file is driving `python=3.9` despite `python=3.8` being requested. 

Should probably review to improve stability and package management.

**Comment by mmcky** [comment]
I am getting execution failures when trying to run this locally. 

```
WARNING: Execution Failed: /Users/matthewmckay/repos-collab/lecture-datascience.myst/lectures/pandas/merge.md
WARNING: Execution Failed: /Users/matthewmckay/repos-collab/lecture-datascience.myst/lectures/problem_sets/problem_set_6.md
WARNING: Execution Failed: /Users/matthewmckay/repos-collab/lecture-datascience.myst/lectures/pandas/groupby.md
WARNING: Execution Failed: /Users/matthewmckay/repos-collab/lecture-datascience.myst/lectures/problem_sets/problem_set_7.md
WARNING: Execution Failed: /Users/matthewmckay/repos-collab/lecture-datascience.myst/lectures/applications/working_with_text.md
WARNING: Couldn't find cache key for notebook file lectures/applications/working_with_text.md. Outputs will not be inserted.
  Last execution failed with traceback saved in /Users/matthewmckay/repos-collab/lecture-datascience.myst/lectures/_build/html/reports/working_with_text.log
WARNING: Couldn't find cache key for notebook file lectures/pandas/groupby.md. Outputs will not be inserted.
  Last execution failed with traceback saved in /Users/matthewmckay/repos-collab/lecture-datascience.myst/lectures/_build/html/reports/groupby.log
WARNING: Couldn't find cache key for notebook file lectures/pandas/merge.md. Outputs will not be inserted.
  Last execution failed with traceback saved in /Users/matthewmckay/repos-collab/lecture-datascience.myst/lectures/_build/html/reports/merge.log
WARNING: Couldn't find cache key for notebook file lectures/problem_sets/problem_set_6.md. Outputs will not be inserted.
  Last execution failed with traceback saved in /Users/matthewmckay/repos-collab/lecture-datascience.myst/lectures/_build/html/reports/problem_set_6.log
WARNING: Couldn't find cache key for notebook file lectures/problem_sets/problem_set_7.md. Outputs will not be inserted.
  Last execution failed with traceback saved in /Users/matthewmckay/repos-collab/lecture-datascience.myst/lectures/_build/html/reports/problem_set_7.log
```

**Comment by mmcky** [comment]
Suggests there may be a package that has been updated recently causing a failure?

**Comment by mmcky** [comment]
This is now the case for new builds. So there must have been a package change?

https://github.com/QuantEcon/lecture-datascience.myst/pull/174/checks?check_run_id=2947682717

**Comment by mmcky** [comment]
@jlperla @Alim-faraji there is an issue with the `qeds` package. Looks like the assets haven't been copied over. 

Were these assets uploaded to `s3` only or are they kept somewhere?

**Comment by jlperla** [comment]
Sorry, I have no idea. But the simpler things become and the more coordinated all assets the happier I am.

**Comment by mmcky** [comment]
@jlperla none of the files are `>100mb` shall I move them to the lecture repo for now to fix this issue?

**Comment by jlperla** [comment]
It makes sense to me. But does this require a qeds change? Do we need @sglyon and @cc7768 to do so?

**Comment by mmcky** [comment]
if we add the assets -- no as they are getting fetched from the `datascience.quantecon.org/assets` location in `qed`

**Comment by jlperla** [comment]
Perfect. Then anything which simplifies the deployment toolchain is good in my books! Aws shouldn't be required for anything

**Comment by mmcky** [comment]
I agree. I was suggesting to add the assets to the `qeds` repo itself so the `qeds` package was self-contained. But that would require updates to the `qed` package

**Comment by jlperla** [comment]
I defer to other people on the qeds package. I don't entirely understand its purpose, or if some hardcoded urls would serve the same purpose.

**Comment by mmcky** [comment]
I will leave #175 open for a night to see what @cc7768 @sglyon think on this. Then can merge tomorrow to fix the build pathway and broken `qeds` requests if approved.

**Comment by mmcky** [comment]
- [ ] rebuild once `qeds` is released

**Comment by mmcky** [comment]
@jlperla for the data items in the `problem_sets` should they be housed by this `lecture` repo or add it to `qeds` as well.

```
.//problem_sets/problem_set_6.md:df = pd.read_csv("https://datascience.quantecon.org/assets/data/canada_census.csv", header=0, index_col=False)
.//problem_sets/problem_set_6.md:(pd.read_csv("https://datascience.quantecon.org/assets/data/canada_census.csv", header=0, index_col=False)
.//problem_sets/problem_set_6.md:adr = pd.read_csv("https://datascience.quantecon.org/assets/data/WorldBank_AgeDependencyRatio.csv")
.//problem_sets/problem_set_7.md:df = pd.read_csv("https://datascience.quantecon.org/assets/data/density_wage_data.csv")
```

They appear directly referenced by the `lectures` so probably here?

**Comment by jlperla** [comment]
Yes, as discussed I think those are all in the right place.  It iss the others that should be moved :-)

**Comment by mmcky** [comment]
OK -- @jlperla given you may deprecate `qeds` to reduce complexity --  will reopen #175 and merge. That adds all static assets that were on `s3` to the `data` folder managed by `github actions`
