### ISSUE TITLE
Remaining functions calling `qeds`

### ISSUE THREAD

**Issue by wupeifan** [QuantEcon/lecture-datascience.myst#176]
The plot style one `qeds.themes.mpl_style()` seems can be removed safely. However, there are still some lectures fetching data from the `qeds` package, listed below,

1. https://datascience.quantecon.org/pandas/merge.html#case-study `ratings = qeds.data.load("goodreads_ratings")`
2. https://datascience.quantecon.org/pandas/merge.html#book-data `books = qeds.data.load("goodreads_books")`
3. https://datascience.quantecon.org/pandas/merge.html#extra-example-airline-delays `air_perf = qeds.load("airline_performance_dec16")[["CRSDepTime", "Carrier", "CarrierDelay", "ArrDelay"]]`
4. https://datascience.quantecon.org/pandas/merge.html#extra-example-airline-delays `carrier_code = qeds.load("airline_carrier_codes")`
5. https://datascience.quantecon.org/pandas/groupby.html#case-study-airline-delays `air_dec = qeds.load("airline_performance_dec16")`
6. https://datascience.quantecon.org/pandas/groupby.html#exercise-cohort-analysis-using-shopify-data `orders = qeds.data.shopify.simulate_orders(500000)`
7. https://datascience.quantecon.org/applications/regression.html `colors = qeds.themes.COLOR_CYCLE`

So there are three types overall: 1) Fetching hardcoded data from `qeds` package itself, in `merge` and `groupby` lectures; 2) Fetching a simulated data (item 6 above); 3) some plotting styles (`mpl_style` and item 7 above).

**Comment by wupeifan** [comment]
The data retrievers are all from https://github.com/QuantEcon/qeds/blob/master/qeds/data/retrievers.py. By running corresponding codes @Alim-faraji you should be able to resolve items 1-5 above. (notice that we can first fetch the full dataframe for item 3). For item 6, just use the simulated version and save it somewhere

**Comment by wupeifan** [comment]
The data part will be resolved through PR #175

**Comment by wupeifan** [comment]
#175 is not merged, and we have other plotting functions to get rid of.

**Comment by Alim-faraji** [comment]
[`lectures/applications/regression.md`](https://github.com/QuantEcon/lecture-datascience.myst/blob/main/lectures/applications/regression.md) uses `qeds` to set color palette and plot template. I think we can remove the template, but we can't just blindly remove the colors. It is used on several occasions in that lecture.

**Comment by wupeifan** [comment]
@Alim-faraji Try removing everything first to see whether it generates a good figure. You can actually try that in our current notebooks, as you only need to comment out those qeds lines and re-run them

**Comment by wupeifan** [comment]
The colors don't have to be the same as what we had before.

**Comment by Alim-faraji** [comment]
I tried to run a [notebook](https://datascience.quantecon.org/applications/regression.htmlhttps://datascience.quantecon.org/applications/regression.html), but it can't read `https://raw.githubusercontent.com/QuantEcon/lecture-datascience.myst/main/lectures/applications/kc_house_data.csv`, because such a file doesn't exist (404: Not found). However, I'm not sure about it. In the lectures, the output seems to be generated with no error. But I can't run that code in the notebook. Any ideas?

**Comment by wupeifan** [comment]
Well, the data is here https://github.com/QuantEcon/lecture-datascience.myst/tree/gh-pages/assets/data. The link to the notebook is not updated because there's no new tagged release? So tag a version to release first

**Comment by wupeifan** [comment]
It's exactly because the notebooks are not synchronized simultaneously, which we should do.

**Comment by wupeifan** [comment]
resolved by recent PRs
