### ISSUE TITLE
Invalid tex in regression lecture (and others?)

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-datascience.myst#181]
The regression lecture is using unescaped latex in a name.  This seems to work in the html renderer, but not in the katex one used in vscode jupyter notebooks.

That is,
```latex
$$
\log(\text{price}) = \beta_0 + \beta_1 \text{sqft_living} + \epsilon
$$
```
is incorrect and should be
```latex
$$
\log(\text{price}) = \beta_0 + \beta_1 \text{sqft\_living} + \epsilon
$$
```
or something similar.

We should look to see if there are other locations that could have this issue.

**Comment by jlperla** [comment]
See https://github.com/QuantEcon/lecture-datascience.myst/blob/main/lectures/applications/regression.md

Is there a simple regex you could try in vscode to globally look for `\text{` followed by a string followed by `\` followed by more string, followed by `}`?  If it is tricky to do, we can just fix them slowly.  I am bad at regex so not sure if this is easy or not, but not worth more than 5 minutes.

**Comment by jbrightuniverse** [comment]
What we want is to find all incorrect instances, right? So would a better search string be searching for a `_` between `\text{` and `}` rather than a `\`?

**Comment by jlperla** [comment]
Yes that is what I meant!  Thanks!

**Comment by jlperla** [comment]
But like I said, not worth more than 5 minutes.

The way to test this all is to generate these and check that it doesn't break in HTML, then with the deployed notebooks load them in `vscode` and its jupyter and see if it has a `KaTeX` parse error.

**Comment by jbrightuniverse** [comment]
Saving for my reference later: a working regex for this is:

`(?<=\\text\{)[^\}]*?(?=_).*?(?=\})`

(ensures phrase starts with `\text{`, ensures there is no `}` before a `_`, and after the `_`, has a closing `}`)

**Comment by wupeifan** [comment]
is this one updated already?
