### ISSUE TITLE
Add in a vscode badge in the the theme

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-datascience.myst#185]
See https://open.vscode.dev/ 

Is it possible to have this in one form or another?  I am finding the jupyter support in vscode to be excellent these days.

Just to be clear, this would open the notebook repo.  Something like [![Open in Visual Studio Code](https://open.vscode.dev/badges/open-in-vscode.svg)](https://open.vscode.dev/QuantEcon/lecture-datascience.notebooks)

with the source 
```md
[![Open in Visual Studio Code](https://open.vscode.dev/badges/open-in-vscode.svg)](https://open.vscode.dev/QuantEcon/lecture-datascience.notebooks)
```

I am setting this to be low priority until we see if this feature is mature or not.  It uses https://code.visualstudio.com/blogs/2021/06/10/remote-repositories  which might be very new.

**Comment by doctor-phil** [comment]
This is worth revisiting. Many students strongly prefer vscode to jupyterlab, and the link above seems to still be working over a year later. I'm going to change this to be un-low-priority. @mmcky @AakashGfude may have input since this is theme-related

**Comment by jlperla** [comment]
Just to make sure we are on the same page, vscode mostly  works great - although there are some quirks with rendering latex. But this link thing is for the online github codespaces (which runs the full vscode in the browser!). It is pretty awesome, but it isn't free anymore so it might be limited appeal. There is free support for classrooms with https://github.blog/2022-05-09-prepare-for-next-semester-with-github-global-campus-and-codespaces/ but my guess is that it is better to stick with whatvwe IT people are willing to support - eg, jupyterhub

**Comment by doctor-phil** [comment]
Gotcha. I tried it out earlier and thought the online vscode would have been a good option to have. But not being free is a dealbreaker. In that case, I'll close this issue

**Comment by jlperla** [comment]
Lets leave it here as low priority instead.  It is still useful, just not high until we have easier access to github education free versions.

**Comment by jlperla** [comment]
The main feature removed in vscode/github codespaces updates.  Probably a new way to do it which we can revisit alternatives later.
