### ISSUE TITLE
BUG: Downloading pages as ipynb files does not work

### ISSUE THREAD

**Issue by giorgi-tsu** [QuantEcon/lecture-datascience.myst#189]
When I click "Download Notebook" button at the top right corner of any page it starts donwloading but then says "Failed- No file".

As an example you can replicate the same issue and try downloading this page: https://datascience.quantecon.org/pandas/intro.html

Is it no longer possible to keep this lectures offline? 

The pdf version of each series that was initally available (somewhere in 2019) was a great option for those who do not have constant access to the itnernet (the case which is very relevant in todays circumstances).

**Comment by wupeifan** [comment]
On which page did you encounter this issue?

**Comment by mmcky** [comment]
thanks for reporting this @giorgi-tsu 

I can replicate the issue -- it seems like the file is referenced for download by:

```
https://datascience.quantecon.org/python_fundamentals/_notebooks/python_fundamentals/collections.ipynb
```

@AakashGfude I think this is a theme issue as the `_notebooks` folder is at the `root` level so we should have

```
https://datascience.quantecon.org/_notebooks/python_fundamentals/collections.ipynb
```

where `_notebooks` contains a copy of the project (with nested folders).

**Comment by giorgi-tsu** [comment]
> On which page did you encounter this issue?

I update the issue description with the link to the page. 

Here for example: https://datascience.quantecon.org/pandas/intro.html

But this issue exists on almost all pages I tried.
