### ISSUE TITLE
ENH: Enable book style PDF

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-datascience.myst#190]
We have had some requests to enable the `book` style PDF (via LaTeX) build.

**Comment by giorgi-tsu** [comment]
This would be great. 

Some time ago it was possible for example to get each one of these books https://quantecon.org/lectures/ as a standalone PDF version. 

I currently have PDF version of "Python Programming for Economics and Finance" 2019. However, as of now none of them are available to download as a signle PDF book. 

Returning back this option would be great for people who have their environments ready and would like to study stuff offline while traveling or for people who do not have stable internet connection. 

Thanks,
Giorgi.

**Comment by jstac** [comment]
Thanks for your feedback @giorgi-tsu , it's much appreciated.   We'll get these back up for readers as soon as possible.  @mmcky and @AakashGfude have assigned time for this early next week.

**Comment by mmcky** [comment]
> I currently have PDF version of "Python Programming for Economics and Finance" 2019. However, as of now none of them are available to download as a signle PDF book.

@giorgi-tsu only the `datascience` and `julia` projects are lacking support for the book style PDF. 

If you click on the file icon (top right):

![Screen Shot 2021-10-17 at 2 54 51 pm](https://user-images.githubusercontent.com/8263752/137610434-823e4fbb-8b0f-42e1-b0fb-4dcb96685f97.png)

you will see a `Book (PDF)` option that links to the pdf such as:

[quantecon-python-programming.pdf](https://github.com/QuantEcon/lecture-datascience.myst/files/7358694/quantecon-python-programming.pdf)

**Comment by jstac** [comment]
Thanks for working on this @mmcky .  This one is also missing: https://jstac.github.io/continuous_time_mcs/intro.html

**Comment by mmcky** [comment]
Thanks @jstac 👍  -- got that issue here https://github.com/jstac/continuous_time_mcs/issues/94

**Comment by AakashGfude** [comment]
The book pdf build for datascience should work error free after merging this PR:- https://github.com/QuantEcon/lecture-datascience.myst/pull/193 .
