### ISSUE TITLE
Reliance on third-party servers for lectures involving web data

### ISSUE THREAD

**Issue by doctor-phil** [QuantEcon/lecture-datascience.myst#212]
There have been intermittent build failures involving lectures that rely on outside servers (e.g. working_with_text makes requests to http://geogratis.gc.ca/ for geolocation services)

This creates a lot of instability with the builds. They are frequently failing due to transient 502 gateway or server timeout errors with external services. 

It would be hard to eliminate this issue entirely because of the importance of the internet data in this course. But it's worth considering how we might reduce these dependencies, or create a reliable failsafe to complete the build in case these dependencies are offline, or undergo some changes to their API that depreciates the lecture code

See, e.g.
[working_with_text.log](https://github.com/QuantEcon/lecture-datascience.myst/files/9768130/working_with_text.log)

**Comment by mmcky** [comment]
We have had similar issues on our site. 
We have moved some data over to caching the data locally and fetching from raw.github. But hard to eliminate entirely.

**Comment by doctor-phil** [comment]
Mostly fixed in latest publish
