### ISSUE TITLE
Remove sphinx-exercise dependency

### ISSUE THREAD

**Issue by aadsouza** [QuantEcon/lecture-datascience.myst#33]
- Change exercise section at bottom of each lecture to vanilla markdown sections.
- Change "see exercise below" `exercise` directives to native jupyter-book `note` directives.

edit:
- Change "see exercise below" `exercise` directives to native jupyter-book ~~`note`~~ `admonition` directives with exercise title.
- `code-block` to executable `code-cell`

**Comment by arnavs** [comment]
Thanks for writing this up.

**Comment by aadsouza** [comment]
see #35 #36 #37
