### ISSUE TITLE
Change Cell-Block into Cell-Code

### ISSUE THREAD

**Issue by WenxinM** [QuantEcon/lecture-datascience.myst#34]
When changing the exercise sections to markdown blocks, we notice that there are some `code-block` used in the text (not in the special content blocks). If the `code-block` is not executable, we might want to change all/some of the `code-block` into `code-cell` depending on the content.

**Comment by WenxinM** [comment]
Another thing to check: some of the `code-cell` do not seem to be executable, no output shows up

**Comment by aadsouza** [comment]
fixed two lectures in fundamentals; created new issue for missing outputs
