### ISSUE TITLE
code-cell does not render outputs

### ISSUE THREAD

**Issue by WenxinM** [QuantEcon/lecture-datascience.myst#38]
On the website, most of the code-cell do not render outputs.

Outputs can be generated in the Python Fundamentals (not in Basics), 
Outputs cannot be rendered in Applications and Pandas (except for Index), Scientific Computing (except for Intro to Numpy)

**Comment by WenxinM** [comment]
@arnavs

**Comment by arnavs** [comment]
Fixed by moving away from `jupyter-cache` due to execution bugs there
