### ISSUE TITLE
Homepage and Links to the Previous Projects

### ISSUE THREAD

**Issue by WenxinM** [QuantEcon/lecture-datascience.myst#45]
The homepage is still under construction. It is blank right now and we need to add:

- [x] text
- [x] links to VSE and to the previous projects 
- [x] contributors and links to their website
- [ ] icons of and links to the 5 main chapters

Also, in the lecture Course Description, there should be a link to the previous project as well, which will be added once the website for the previous projects is migrated.

**Comment by aadsouza** [comment]
no need for icons.
