### ISSUE TITLE
Links and Screenshots based on the Old Website

### ISSUE THREAD

**Issue by WenxinM** [QuantEcon/lecture-datascience.myst#46]
- [x] Some links in the first chapter are links to the old website.
- [ ] Some screenshots are from the old website as well.

**Comment by WenxinM** [comment]
The screenshots issue is related to the launch button. It can be updated after we merge the PR by A.akash

**Comment by WenxinM** [comment]
After updating the screenshots, replace the image links with internal GitHub links

**Comment by WenxinM** [comment]
screenshots in lecture _local installation_ need to be updated: python version from 3.7 to 3.8

**Comment by arnavs** [comment]
Reorganizing issues a bit
