### ISSUE TITLE
Get the frontpage text and old projects into the soruce

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-datascience.myst#49]

**Comment by arnavs** [comment]
As discussed in the thread @aadsouza @WenxinM — making this a priority

**Comment by WenxinM** [comment]
Frontpage text added.

**Comment by WenxinM** [comment]
There is this nice **toolbar on the front page**, created by `toctree` in the source ds repo. However, in the Jupyterbook, it is generated as a table of contents that shows up on the side: https://jupyterbook.org/explain/sphinx.html?highlight=toctree#how-does-jupyter-book-differ-from-sphinx

**Comment by aadsouza** [comment]
@WenxinM has added previous projects for UBC + added previous projects for HUST and contributors page.
