### ISSUE TITLE
Bug in generated notebooks

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-datascience.myst#57]
- Images render as links
- Linked to old website
- paths are off

**Comment by aadsouza** [comment]
@arnavs https://github.com/executablebooks/MyST-NB/issues/230

**Comment by jlperla** [comment]
@aadsouza  We need to make sure there are no embedded things in the document as attachment.  These should always refer to URLs on the web (just not on googleapis if possible.  We can have these things deployed on the github repo or others.  Maybe @mmcky  has a workflow for how to store links to assets?).

**Comment by mmcky** [comment]
@jlperla for generated notebooks we:

1. copy the notebooks to `_notebooks` folder in `_builds/html`
2. push updated notebooks to `lecture-{series}.notebooks` for access by binder.

We currently do this in the `github actions`. I can help set that up. But we would like to build a `website` target for `jupyterbook` that coordinates the generation of all these build assets and then puts them in the correct place. That is on our `todo` list.

**Comment by jlperla** [comment]
Thanks @mmcky   .  For this @arnavs  I am not sure where the stuff should be, but my instincts are that it shouldn't be notebook specific.  Maybe we just need a better static asset.  Not sure.  So if this requires a non-trivial change, it means we are probably doing something wrong.

**Comment by arnavs** [comment]
Reorganizing issues a bit
