### ISSUE TITLE
xgboost and other errors in heterogenous effects

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-datascience.myst#58]
https://quantecon.github.io/lecture-datascience.myst/applications/heterogeneity.html

Probably needs `xgboost` or whatnot in the einvorment.

**Comment by aadsouza** [comment]
found another: https://quantecon.github.io/lecture-datascience.myst/applications/regression.html
probably needs `graphviz` in the environment.

**Comment by aadsouza** [comment]
issue is duplicate of #48
