### ISSUE TITLE
Go page by page looking for bugs and errors relative to the current one

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-datascience.myst#59]
I saw an issue in the heterogenous effects model (see #58 ).  I think that you guys need to go through every one of the pages looking at the existing one on the other screen and make sure you don't see any issues.  Post bugs here as you find them, and then we can fix them one-by-one.

@arnavs @WenxinM  @aadsouza

**Comment by aadsouza** [comment]
issues created for bugs
