### ISSUE TITLE
working with text is full width

### ISSUE THREAD

**Issue by aadsouza** [QuantEcon/lecture-datascience.myst#68]
full width text, code, and output - awkward relative to every other lecture that remains within margins
![Screen Shot 2021-04-14 at 9 27 43 PM](https://user-images.githubusercontent.com/59585791/114814175-8052c600-9d68-11eb-8454-49571b7ae39d.png)

**Comment by aadsouza** [comment]
also working with text is the only lecture where the launch buttons look weird under the theme.
![Screen Shot 2021-05-07 at 11 21 11 PM](https://user-images.githubusercontent.com/59585791/117529184-01c5fe80-af8b-11eb-8ce0-97d5456179f9.png)

**Comment by WenxinM** [comment]
It works fine when building locally on Windows, but not remotely.

**Comment by aadsouza** [comment]
@mmcky any tips on this one?

**Comment by mmcky** [comment]
@aadsouza the broken theme suggests there are some `javascript` elements that may not be loading correctly. Are any of the outputs `javascript` style outputs (i.e. interactive plots etc.)?

**Comment by aadsouza** [comment]
@mmcky yeah there are a couple of interactive plots

**Comment by mmcky** [comment]
Also you may want to set the table size defaults globally for `pandas` to control the width of the tables.

**Comment by mmcky** [comment]
@AakashGfude there are some javascript style objects here. I know we fixed issues with `ipywidgets` but perhaps you could take a look here to see if these rich `javascript` objects are causing issues with the theme loading.

**Comment by mmcky** [comment]
> @mmcky yeah there are a couple of interactive plots

@aadsouza do they need a running kernel or are they `pure` javascript objects do you know?

**Comment by mmcky** [comment]
it looks like these are issues with the current site as well (except for the theme not loading)

https://datascience.quantecon.org/applications/working_with_text.html

**Comment by aadsouza** [comment]
> > @mmcky yeah there are a couple of interactive plots
> 
> @aadsouza do they need a running kernel or are they `pure` javascript objects do you know?

i think they need a kernel. they're outputs for `folium` and `pyLDAvis` among others

**Comment by mmcky** [comment]
> > > @mmcky yeah there are a couple of interactive plots
> > 
> > 
> > @aadsouza do they need a running kernel or are they `pure` javascript objects do you know?
> 
> i think they need a kernel. they're outputs for `folium` and `pyLDAvis` among others

OK -- haven't used those packages -- but a running `kernel` is an issue as some of these rich object type actually inject malformed javascript. 

What I would recommend is:

1. Add in a static view of the default output
2. Leave the `code-cell` in the lecture (for download notebooks / runnable environments) but add `remove-output` to the tags

this takes a bit of editing of the lecture -- but is what we have done in `python` as a general rule. @AakashGfude and I will also look at the richer `javascript` objects to see what is causing an issue but it is hard to support all `javascript` outputs in general.
