### ISSUE TITLE
Look for Whitespace Errors

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-datascience.myst#7]
Let's say @WenxinM does the first three sections, and @aadsouza does the last two (the first section, "Introduction", is just one lecture.)

Per @mmcky: 

```
Sometimes a > will crop up in myst files that have been generated by sphinx-tomyst. That is because a lot of users get white space wrong in rst so any form of incorrect indentation wraps items in a block_quote object within the sphinx.ast. So these are something to keep an eye out for.
```

Let's find and fix these if possible. This should be doable based on the source itself. Basically find occurrences of that character and see if they correspond to a valid block quote on the website.

**Comment by aadsouza** [comment]
Pushed whitespace error fix for reshape.md
