### ISSUE TITLE
Invalid links in the notebooks

### ISSUE THREAD

**Issue by WenxinM** [QuantEcon/lecture-datascience.myst#8]
There are two invalid links in the current notebooks, possibly due to the nested structure of the exercise. 

- One is in Lecture Randomness 

([https://datascience.quantecon.org/scientific/randomness.html](url) or [https://5ff76619566d1a00a3e5f162--nervous-villani-f8256d.netlify.app/scientific/randomness.html](url))
There should be a link to the lecture Applied Linear Algebra in exercise 3 but it does not show up. The corresponding code is line 484 in the md file (I couldn't find a way to refer to the codes in the md files):

````{exercise}
**Exercise 3**

Let's revisit the unemployment example from the {doc}`linear algebra lecture <applied_linalg>`.

We'll repeat necessary details here.
````

- The other is in Lecture Introduction to Numpy

There should be a link to the lecture Control Flow in exercise 5. It does not show up here [https://datascience.quantecon.org/scientific/numpy_arrays.html](url) but works as expected here [https://5ff76619566d1a00a3e5f162--nervous-villani-f8256d.netlify.app/scientific/numpy_arrays.html](url). The corresponding code is line 417 in the md file:

````{exercise}
**Exercise 5**

Let's revisit a bond pricing example we saw in {doc}`Control flow <../python_fundamentals/control_flow>`.
````
@arnavs

**Comment by aadsouza** [comment]
Works as expected on `.myst`. Links not generated on live source ds website. May need to review `.rst` files.

**Comment by aadsouza** [comment]
see #25 #26 #27 #28

**Comment by WenxinM** [comment]
This issue has been transferred to the source repo.
