### ISSUE TITLE
PS8 requires `ahs-train.csv`

### ISSUE THREAD

**Issue by aadsouza** [QuantEcon/lecture-datascience.myst#81]
moved `prep_ahs.R` from source repo, but it needs to run to generate the training and testing datasets.

**Comment by aadsouza** [comment]
note that testing dataset is used for evaluation

**Comment by wupeifan** [comment]
I have those files if you need them. Can make a PR real quick -- under which directory should I put it? Maybe just under problem sets?

**Comment by aadsouza** [comment]
under problem sets should be good. do we want to keep the R file?

**Comment by wupeifan** [comment]
Yeah just keep the R file there should be fine, I think.
See the PR above which should fix this thing

**Comment by aadsouza** [comment]
merged #86. thanks @wupeifan
