### ISSUE TITLE
missing "hidden" answer (transferred from source)

### ISSUE THREAD

**Issue by aadsouza** [QuantEcon/lecture-datascience.myst#87]
https://datascience.quantecon.org/pandas/reshape.html

Exercise 1 here says "Don't spend too much time on this... if you get stuck, open up this markdown cell, and you will see our answer hidden." where this is just boldface text.

**Comment by wupeifan** [comment]
The answer is hidden there, once you open it with Jupyter lab/notebook. You won't be able to "open up the cell" on a webpage, unfortunately.

That particular markdown cell goes like this
``` markdown
Don't spend too much time on this... if you get stuck, open up **this**
markdown cell, and you will see our answer hidden.

**Hint**: You might need to add `.sort_index(axis=1)` after you are
finished to get the columns in the same order.

**Hint**: You may not end up with a `variable` header on the second
level of column labels. This is ok.

<div style="display: none;">

`bball.drop("TeamName", axis=1).set_index(["Year", "Player", "Team"]).stack().unstack(level=[1, 3, 2]).sort_index(axis=1)`

</div>
```
So you can see the answer is indeed hidden here

**Comment by aadsouza** [comment]
this is what it looks like with the notebook from [here](https://github.com/QuantEcon/lecture-datascience.notebooks/blob/main/pandas/reshape.ipynb)
![Screen Shot 2021-05-07 at 2 41 16 PM](https://user-images.githubusercontent.com/59585791/117511386-79237000-af42-11eb-99e1-c5483b5cc90e.png)

should probably add ```<div style="display: none;"> `foo` </div>``` back in.

an alternative could be to play around with this https://jupyterbook.org/interactive/hiding.html?highlight=hidden

**Comment by wupeifan** [comment]
Oh, I see. Yes in the versions that are now working, the hidden line was well quoted. I don't know about the new ones that you guys are working on, but I guess that line was removed by accident because all HTML-related lines are deleted.

**Comment by aadsouza** [comment]
closing for now with workaround - will reopen if we find a better soln
