### ISSUE TITLE
Fix Citations

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-datascience.myst#9]

**Comment by arnavs** [comment]
@aadsouza @WenxinM I know we need to bring in the `applications.bib` from the RST, but for some reason the `{cite}` directives are throwing warnings here. 

If you can figure out what's going on (e.g. how to migrate over the references to Jupyter Book), I'd appreciate it: 

https://jupyterbook.org/content/citations.html

**Comment by aadsouza** [comment]
Pushed citation fixes for `regression.md`, `recidivism.md`, `heterogeneity.md`, and `ml_in_economics.md`.

**Comment by arnavs** [comment]
Great work. Looks good to me.

**Comment by aadsouza** [comment]
doesn't seem to be fixed now on https://quantecon.github.io/lecture-datascience.myst/

**Comment by WenxinM** [comment]
fixed by adding the `sphinxcontrib.bibtex` extension in the environment.yml

**Comment by aadsouza** [comment]
works locally, not on built website here

**Comment by aadsouza** [comment]
works with pinned version <2.0.0
